name: 'Add existing app or test app'

run-name: "Add existing app or test app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      url:
        description: Direct Download Url of .app or .zip file
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for Pull Request/COMMIT
        type: boolean

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  AddExistingAppOrTestApp:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@issue555
        with:
          shell: powershell
          eventId: "DO0090"

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@main
        if: github.event.inputs.useGhTokenWorkflow == 'true'
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          get: keyVaultName,ghTokenWorkflowSecretName

      - name: Read secrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@main
        if: github.event.inputs.useGhTokenWorkflow == 'true'
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: CalculateToken
        id: CalculateToken
        env:
          useGhTokenWorkflow: ${{ github.event.inputs.useGhTokenWorkflow }}
        run: |
          if ($env:useGhTokenWorkflow -eq 'true') {
            $ghToken = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:GHTOKENWORKFLOW))
          } else {
            $ghToken = '${{ secrets.GITHUB_TOKEN }}'
          }
          Add-Content -Path $env:GITHUB_OUTPUT -Value "ghToken=$ghToken"

      - name: Add existing app
        uses: freddydk/AL-Go/Actions/AddExistingApp@issue555
        with:
          shell: powershell
          token: ${{ steps.CalculateToken.outputs.ghToken }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          url: ${{ github.event.inputs.url }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@issue555
        with:
          shell: powershell
          eventId: "DO0090"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
