name: Create a new test app

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      name:
        description: Name
        required: true
        default: '<YourAppName>.Test'         
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range
        required: true
        default: '50000..99999'  
      sampleCode:
        description: Include Sample code (Y/N)
        required: false
        default: 'Y'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: PowerShell

jobs:
  CreateTestApp:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go-Actions/WorkflowInitialize@main
        with:
          eventId: "DO0095"

      - name: Encode parameters
        id: encode
        env:
          name: ${{ github.event.inputs.name }}
          publisher: ${{ github.event.inputs.publisher }}
        run: |
          Write-Host "::set-output name=name::$([Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($ENV:name)))"
          Write-Host "set-output name=name::$([Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($ENV:name)))"
          Write-Host "::set-output name=publisher::$([Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($publisher)))"
          Write-Host "set-output name=publisher::$([Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($publisher)))"

      - name: Creating a new test app
        uses: freddydk/AL-Go-Actions/CreateApp@main
        with:
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          type: 'Test App'
          publisher: ${{ steps.encode.outputs.publisher }}
          name: ${{ steps.encode.outputs.name }}
          idrange: ${{ github.event.inputs.idrange }}
          sampleCode: ${{ github.event.inputs.sampleCode }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: freddydk/AL-Go-Actions/WorkflowPostProcess@main
        with:
          eventId: "DO0095"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
